server:
  port: 8001

spring:
  application:
    name: cloud-provider-hystrix-payment
  devtools:
    restart:
      poll-interval: 2s
      quiet-period: 1s

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka



